export type Area = {
  slug: string;
  nameAr: string;
  nameEn: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  faqQuestion: string;
  faqAnswer: string;
  serviceType: string;
  serviceName: string;
  serviceDescription: string;
  metaTitleEn: string;
  metaDescriptionEn: string;
  introEn: string;
  faqQuestionEn: string;
  faqAnswerEn: string;
  serviceTypeEn: string;
  serviceNameEn: string;
  serviceDescriptionEn: string;
};

/**
 * The 36 neighborhood pages, extracted verbatim from the current
 * buy-used-furniture-[area].html files (title/description/intro/FAQ/JSON-LD
 * fields all differ per area; everything else in the page is shared markup).
 * Slugs cross-checked against vercel.json redirects and coverage-areas.html
 * in the Milestone 0 baseline crawl and Milestone 3 area list — exact match.
 */
export const areas: Area[] = [
  {
    slug: "abu-nassir",
    nameAr: "أبو نصير",
    nameEn: "Abu Nassir",
    metaTitle: "شراء أثاث مستعمل في أبو نصير - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في أبو نصير وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة أبو نصير بالكامل وضواحيها، بالقرب من دوار أبو نصير وشارع الأمير حسن. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في أبو نصير خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة أبو نصير، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة أبو نصير؟",
    faqAnswer: "نعم، نغطي منطقة أبو نصير بالكامل وضواحيها القريبة من دوار أبو نصير وشارع الأمير حسن. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في أبو نصير",
    serviceName: "خدمة شراء الأثاث المستعمل في أبو نصير - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في أبو نصير: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Abu Nassir - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Abu Nassir and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Abu Nassir area and its surroundings in full. With over 60 years of experience, our team reaches you in Abu Nassir quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Abu Nassir, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Abu Nassir area?",
    faqAnswerEn: "Yes, we fully cover Abu Nassir and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Abu Nassir",
    serviceNameEn: "Used Furniture Buying Service in Abu Nassir - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Abu Nassir: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "dahiyat-al-rashid",
    nameAr: "ضاحية الرشيد",
    nameEn: "Dahiyat Al Rashid",
    metaTitle: "شراء أثاث مستعمل في ضاحية الرشيد - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في ضاحية الرشيد وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة ضاحية الرشيد بالكامل وضواحيها، بالقرب من شارع ضاحية الرشيد الرئيسي والمجمعات السكنية المحيطة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في ضاحية الرشيد خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة ضاحية الرشيد، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة ضاحية الرشيد؟",
    faqAnswer: "نعم، نغطي منطقة ضاحية الرشيد بالكامل وضواحيها القريبة من شارع ضاحية الرشيد الرئيسي والمجمعات السكنية المحيطة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في ضاحية الرشيد",
    serviceName: "خدمة شراء الأثاث المستعمل في ضاحية الرشيد - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في ضاحية الرشيد: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Dahiyat Al Rashid - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Dahiyat Al Rashid and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Dahiyat Al Rashid area and its surroundings in full. With over 60 years of experience, our team reaches you in Dahiyat Al Rashid quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Dahiyat Al Rashid, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Dahiyat Al Rashid area?",
    faqAnswerEn: "Yes, we fully cover Dahiyat Al Rashid and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Dahiyat Al Rashid",
    serviceNameEn: "Used Furniture Buying Service in Dahiyat Al Rashid - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Dahiyat Al Rashid: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "daboug",
    nameAr: "دابوق",
    nameEn: "Daboug",
    metaTitle: "شراء أثاث مستعمل في دابوق - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في دابوق وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة دابوق بالكامل وضواحيها، بالقرب من طريق دابوق ومنطقة الفلل الراقية. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في دابوق خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة دابوق، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة دابوق؟",
    faqAnswer: "نعم، نغطي منطقة دابوق بالكامل وضواحيها القريبة من طريق دابوق ومنطقة الفلل الراقية. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في دابوق",
    serviceName: "خدمة شراء الأثاث المستعمل في دابوق - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في دابوق: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Daboug - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Daboug and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Daboug area and its surroundings in full. With over 60 years of experience, our team reaches you in Daboug quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Daboug, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Daboug area?",
    faqAnswerEn: "Yes, we fully cover Daboug and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Daboug",
    serviceNameEn: "Used Furniture Buying Service in Daboug - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Daboug: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "um-al-summaq",
    nameAr: "أم السماق",
    nameEn: "Um Al Summaq",
    metaTitle: "شراء أثاث مستعمل في أم السماق - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في أم السماق وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة أم السماق بالكامل وضواحيها، بالقرب من دوار أم السماق ومجمعات الأبراج السكنية. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في أم السماق خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة أم السماق، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة أم السماق؟",
    faqAnswer: "نعم، نغطي منطقة أم السماق بالكامل وضواحيها القريبة من دوار أم السماق ومجمعات الأبراج السكنية. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في أم السماق",
    serviceName: "خدمة شراء الأثاث المستعمل في أم السماق - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في أم السماق: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Um Al Summaq - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Um Al Summaq and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Um Al Summaq area and its surroundings in full. With over 60 years of experience, our team reaches you in Um Al Summaq quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Um Al Summaq, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Um Al Summaq area?",
    faqAnswerEn: "Yes, we fully cover Um Al Summaq and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Um Al Summaq",
    serviceNameEn: "Used Furniture Buying Service in Um Al Summaq - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Um Al Summaq: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "gardens",
    nameAr: "الجاردنز",
    nameEn: "Gardens",
    metaTitle: "شراء أثاث مستعمل في الجاردنز - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الجاردنز وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الجاردنز بالكامل وضواحيها، بالقرب من شارع الجاردنز ومنطقة الأعمال المحيطة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الجاردنز خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الجاردنز، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الجاردنز؟",
    faqAnswer: "نعم، نغطي منطقة الجاردنز بالكامل وضواحيها القريبة من شارع الجاردنز ومنطقة الأعمال المحيطة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الجاردنز",
    serviceName: "خدمة شراء الأثاث المستعمل في الجاردنز - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الجاردنز: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Gardens - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Gardens and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Gardens area and its surroundings in full. With over 60 years of experience, our team reaches you in Gardens quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Gardens, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Gardens area?",
    faqAnswerEn: "Yes, we fully cover Gardens and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Gardens",
    serviceNameEn: "Used Furniture Buying Service in Gardens - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Gardens: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "sports-city",
    nameAr: "المدينة الرياضية",
    nameEn: "Sports City",
    metaTitle: "شراء أثاث مستعمل في المدينة الرياضية - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في المدينة الرياضية وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة المدينة الرياضية بالكامل وضواحيها، بالقرب من دوار المدينة الرياضية واستاد الملك عبدالله. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في المدينة الرياضية خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة المدينة الرياضية، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة المدينة الرياضية؟",
    faqAnswer: "نعم، نغطي منطقة المدينة الرياضية بالكامل وضواحيها القريبة من دوار المدينة الرياضية واستاد الملك عبدالله. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في المدينة الرياضية",
    serviceName: "خدمة شراء الأثاث المستعمل في المدينة الرياضية - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في المدينة الرياضية: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Sports City - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Sports City and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Sports City area and its surroundings in full. With over 60 years of experience, our team reaches you in Sports City quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Sports City, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Sports City area?",
    faqAnswerEn: "Yes, we fully cover Sports City and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Sports City",
    serviceNameEn: "Used Furniture Buying Service in Sports City - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Sports City: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "tabarbour",
    nameAr: "طبربور",
    nameEn: "Tabarbour",
    metaTitle: "شراء أثاث مستعمل في طبربور - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في طبربور وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة طبربور بالكامل وضواحيها، بالقرب من شارع طبربور الرئيسي ومحطة الباصات. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في طبربور خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة طبربور، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة طبربور؟",
    faqAnswer: "نعم، نغطي منطقة طبربور بالكامل وضواحيها القريبة من شارع طبربور الرئيسي ومحطة الباصات. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في طبربور",
    serviceName: "خدمة شراء الأثاث المستعمل في طبربور - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في طبربور: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Tabarbour - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Tabarbour and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Tabarbour area and its surroundings in full. With over 60 years of experience, our team reaches you in Tabarbour quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Tabarbour, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Tabarbour area?",
    faqAnswerEn: "Yes, we fully cover Tabarbour and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Tabarbour",
    serviceNameEn: "Used Furniture Buying Service in Tabarbour - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Tabarbour: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "university-street",
    nameAr: "الجامعة",
    nameEn: "University Street",
    metaTitle: "شراء أثاث مستعمل في الجامعة - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الجامعة وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الجامعة بالكامل وضواحيها، بالقرب من منطقة الجامعة الأردنية وشارع الجامعة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الجامعة خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الجامعة، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الجامعة؟",
    faqAnswer: "نعم، نغطي منطقة الجامعة بالكامل وضواحيها القريبة من منطقة الجامعة الأردنية وشارع الجامعة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الجامعة",
    serviceName: "خدمة شراء الأثاث المستعمل في الجامعة - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الجامعة: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in University Street - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in University Street and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the University Street area and its surroundings in full. With over 60 years of experience, our team reaches you in University Street quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in University Street, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the University Street area?",
    faqAnswerEn: "Yes, we fully cover University Street and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in University Street",
    serviceNameEn: "Used Furniture Buying Service in University Street - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in University Street: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "deir-ghbar",
    nameAr: "دير غبار",
    nameEn: "Deir Ghbar",
    metaTitle: "شراء أثاث مستعمل في دير غبار - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في دير غبار وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة دير غبار بالكامل وضواحيها، بالقرب من منطقة دير غبار السكنية. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في دير غبار خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة دير غبار، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة دير غبار؟",
    faqAnswer: "نعم، نغطي منطقة دير غبار بالكامل وضواحيها القريبة من منطقة دير غبار السكنية. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في دير غبار",
    serviceName: "خدمة شراء الأثاث المستعمل في دير غبار - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في دير غبار: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Deir Ghbar - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Deir Ghbar and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Deir Ghbar area and its surroundings in full. With over 60 years of experience, our team reaches you in Deir Ghbar quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Deir Ghbar, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Deir Ghbar area?",
    faqAnswerEn: "Yes, we fully cover Deir Ghbar and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Deir Ghbar",
    serviceNameEn: "Used Furniture Buying Service in Deir Ghbar - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Deir Ghbar: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "um-uthaina",
    nameAr: "أم أذينة",
    nameEn: "Um Uthaina",
    metaTitle: "شراء أثاث مستعمل في أم أذينة - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في أم أذينة وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة أم أذينة بالكامل وضواحيها، بالقرب من دوار أم أذينة وشارع مكة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في أم أذينة خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة أم أذينة، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة أم أذينة؟",
    faqAnswer: "نعم، نغطي منطقة أم أذينة بالكامل وضواحيها القريبة من دوار أم أذينة وشارع مكة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في أم أذينة",
    serviceName: "خدمة شراء الأثاث المستعمل في أم أذينة - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في أم أذينة: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Um Uthaina - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Um Uthaina and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Um Uthaina area and its surroundings in full. With over 60 years of experience, our team reaches you in Um Uthaina quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Um Uthaina, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Um Uthaina area?",
    faqAnswerEn: "Yes, we fully cover Um Uthaina and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Um Uthaina",
    serviceNameEn: "Used Furniture Buying Service in Um Uthaina - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Um Uthaina: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "rabia",
    nameAr: "الرابية",
    nameEn: "Rabia",
    metaTitle: "شراء أثاث مستعمل في الرابية - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الرابية وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الرابية بالكامل وضواحيها، بالقرب من منطقة الرابية والسفارات المحيطة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الرابية خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الرابية، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الرابية؟",
    faqAnswer: "نعم، نغطي منطقة الرابية بالكامل وضواحيها القريبة من منطقة الرابية والسفارات المحيطة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الرابية",
    serviceName: "خدمة شراء الأثاث المستعمل في الرابية - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الرابية: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Rabia - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Rabia and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Rabia area and its surroundings in full. With over 60 years of experience, our team reaches you in Rabia quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Rabia, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Rabia area?",
    faqAnswerEn: "Yes, we fully cover Rabia and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Rabia",
    serviceNameEn: "Used Furniture Buying Service in Rabia - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Rabia: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "sweifieh",
    nameAr: "الصويفية",
    nameEn: "Sweifieh",
    metaTitle: "شراء أثاث مستعمل في الصويفية - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الصويفية وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الصويفية بالكامل وضواحيها، بالقرب من شارع الصويفية ومجمعات التسوق. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الصويفية خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الصويفية، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الصويفية؟",
    faqAnswer: "نعم، نغطي منطقة الصويفية بالكامل وضواحيها القريبة من شارع الصويفية ومجمعات التسوق. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الصويفية",
    serviceName: "خدمة شراء الأثاث المستعمل في الصويفية - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الصويفية: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Sweifieh - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Sweifieh and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Sweifieh area and its surroundings in full. With over 60 years of experience, our team reaches you in Sweifieh quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Sweifieh, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Sweifieh area?",
    faqAnswerEn: "Yes, we fully cover Sweifieh and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Sweifieh",
    serviceNameEn: "Used Furniture Buying Service in Sweifieh - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Sweifieh: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "bayader",
    nameAr: "البيادر",
    nameEn: "Bayader",
    metaTitle: "شراء أثاث مستعمل في البيادر - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في البيادر وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة البيادر بالكامل وضواحيها، بالقرب من منطقة البيادر ومحيطها. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في البيادر خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة البيادر، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة البيادر؟",
    faqAnswer: "نعم، نغطي منطقة البيادر بالكامل وضواحيها القريبة من منطقة البيادر ومحيطها. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في البيادر",
    serviceName: "خدمة شراء الأثاث المستعمل في البيادر - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في البيادر: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Bayader - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Bayader and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Bayader area and its surroundings in full. With over 60 years of experience, our team reaches you in Bayader quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Bayader, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Bayader area?",
    faqAnswerEn: "Yes, we fully cover Bayader and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Bayader",
    serviceNameEn: "Used Furniture Buying Service in Bayader - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Bayader: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "wadi-seer",
    nameAr: "وادي السير",
    nameEn: "Wadi Seer",
    metaTitle: "شراء أثاث مستعمل في وادي السير - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في وادي السير وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة وادي السير بالكامل وضواحيها، بالقرب من شارع وادي السير الرئيسي. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في وادي السير خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة وادي السير، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة وادي السير؟",
    faqAnswer: "نعم، نغطي منطقة وادي السير بالكامل وضواحيها القريبة من شارع وادي السير الرئيسي. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في وادي السير",
    serviceName: "خدمة شراء الأثاث المستعمل في وادي السير - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في وادي السير: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Wadi Seer - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Wadi Seer and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Wadi Seer area and its surroundings in full. With over 60 years of experience, our team reaches you in Wadi Seer quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Wadi Seer, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Wadi Seer area?",
    faqAnswerEn: "Yes, we fully cover Wadi Seer and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Wadi Seer",
    serviceNameEn: "Used Furniture Buying Service in Wadi Seer - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Wadi Seer: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "marj-al-hamam",
    nameAr: "مرج الحمام",
    nameEn: "Marj Al Hamam",
    metaTitle: "شراء أثاث مستعمل في مرج الحمام - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في مرج الحمام وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة مرج الحمام بالكامل وضواحيها، بالقرب من دوار مرج الحمام. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في مرج الحمام خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة مرج الحمام، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة مرج الحمام؟",
    faqAnswer: "نعم، نغطي منطقة مرج الحمام بالكامل وضواحيها القريبة من دوار مرج الحمام. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في مرج الحمام",
    serviceName: "خدمة شراء الأثاث المستعمل في مرج الحمام - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في مرج الحمام: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Marj Al Hamam - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Marj Al Hamam and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Marj Al Hamam area and its surroundings in full. With over 60 years of experience, our team reaches you in Marj Al Hamam quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Marj Al Hamam, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Marj Al Hamam area?",
    faqAnswerEn: "Yes, we fully cover Marj Al Hamam and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Marj Al Hamam",
    serviceNameEn: "Used Furniture Buying Service in Marj Al Hamam - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Marj Al Hamam: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "airport-road",
    nameAr: "طريق المطار",
    nameEn: "Airport Road",
    metaTitle: "شراء أثاث مستعمل في طريق المطار - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في طريق المطار وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة طريق المطار بالكامل وضواحيها، بالقرب من طريق المطار والمناطق الصناعية المحيطة. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في طريق المطار خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة طريق المطار، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة طريق المطار؟",
    faqAnswer: "نعم، نغطي منطقة طريق المطار بالكامل وضواحيها القريبة من طريق المطار والمناطق الصناعية المحيطة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في طريق المطار",
    serviceName: "خدمة شراء الأثاث المستعمل في طريق المطار - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في طريق المطار: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Airport Road - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Airport Road and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Airport Road area and its surroundings in full. With over 60 years of experience, our team reaches you in Airport Road quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Airport Road, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Airport Road area?",
    faqAnswerEn: "Yes, we fully cover Airport Road and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Airport Road",
    serviceNameEn: "Used Furniture Buying Service in Airport Road - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Airport Road: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "jabal-amman",
    nameAr: "جبل عمان",
    nameEn: "Jabal Amman",
    metaTitle: "شراء أثاث مستعمل في جبل عمان - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في جبل عمان وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة جبل عمان بالكامل وضواحيها، بالقرب من الدوار الأول والثاني بجبل عمان. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في جبل عمان خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة جبل عمان، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة جبل عمان؟",
    faqAnswer: "نعم، نغطي منطقة جبل عمان بالكامل وضواحيها القريبة من الدوار الأول والثاني بجبل عمان. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في جبل عمان",
    serviceName: "خدمة شراء الأثاث المستعمل في جبل عمان - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في جبل عمان: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Jabal Amman - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Jabal Amman and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Jabal Amman area and its surroundings in full. With over 60 years of experience, our team reaches you in Jabal Amman quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Jabal Amman, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Jabal Amman area?",
    faqAnswerEn: "Yes, we fully cover Jabal Amman and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Jabal Amman",
    serviceNameEn: "Used Furniture Buying Service in Jabal Amman - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Jabal Amman: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "jabal-al-hussein",
    nameAr: "جبل الحسين",
    nameEn: "Jabal Al Hussein",
    metaTitle: "شراء أثاث مستعمل في جبل الحسين - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في جبل الحسين وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة جبل الحسين بالكامل وضواحيها، بالقرب من منطقة جبل الحسين ومجمعها التجاري. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في جبل الحسين خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة جبل الحسين، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة جبل الحسين؟",
    faqAnswer: "نعم، نغطي منطقة جبل الحسين بالكامل وضواحيها القريبة من منطقة جبل الحسين ومجمعها التجاري. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في جبل الحسين",
    serviceName: "خدمة شراء الأثاث المستعمل في جبل الحسين - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في جبل الحسين: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Jabal Al Hussein - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Jabal Al Hussein and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Jabal Al Hussein area and its surroundings in full. With over 60 years of experience, our team reaches you in Jabal Al Hussein quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Jabal Al Hussein, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Jabal Al Hussein area?",
    faqAnswerEn: "Yes, we fully cover Jabal Al Hussein and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Jabal Al Hussein",
    serviceNameEn: "Used Furniture Buying Service in Jabal Al Hussein - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Jabal Al Hussein: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "ain-al-basha",
    nameAr: "عين الباشا",
    nameEn: "Ain Al Basha",
    metaTitle: "شراء أثاث مستعمل في عين الباشا - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في عين الباشا وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة عين الباشا بالكامل وضواحيها، بالقرب من منطقة عين الباشا. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في عين الباشا خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة عين الباشا، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة عين الباشا؟",
    faqAnswer: "نعم، نغطي منطقة عين الباشا بالكامل وضواحيها القريبة من منطقة عين الباشا. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في عين الباشا",
    serviceName: "خدمة شراء الأثاث المستعمل في عين الباشا - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في عين الباشا: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Ain Al Basha - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Ain Al Basha and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Ain Al Basha area and its surroundings in full. With over 60 years of experience, our team reaches you in Ain Al Basha quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Ain Al Basha, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Ain Al Basha area?",
    faqAnswerEn: "Yes, we fully cover Ain Al Basha and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Ain Al Basha",
    serviceNameEn: "Used Furniture Buying Service in Ain Al Basha - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Ain Al Basha: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "al-sarou",
    nameAr: "السرو",
    nameEn: "Al Sarou",
    metaTitle: "شراء أثاث مستعمل في السرو - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في السرو وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة السرو بالكامل وضواحيها، بالقرب من منطقة السرو السكنية. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في السرو خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة السرو، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة السرو؟",
    faqAnswer: "نعم، نغطي منطقة السرو بالكامل وضواحيها القريبة من منطقة السرو السكنية. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في السرو",
    serviceName: "خدمة شراء الأثاث المستعمل في السرو - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في السرو: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Al Sarou - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Al Sarou and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Al Sarou area and its surroundings in full. With over 60 years of experience, our team reaches you in Al Sarou quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Al Sarou, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Al Sarou area?",
    faqAnswerEn: "Yes, we fully cover Al Sarou and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Al Sarou",
    serviceNameEn: "Used Furniture Buying Service in Al Sarou - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Al Sarou: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "fuheis",
    nameAr: "الفحيص",
    nameEn: "Fuheis",
    metaTitle: "شراء أثاث مستعمل في الفحيص - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الفحيص وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الفحيص بالكامل وضواحيها، بالقرب من بلدة الفحيص ومحيطها. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الفحيص خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الفحيص، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الفحيص؟",
    faqAnswer: "نعم، نغطي منطقة الفحيص بالكامل وضواحيها القريبة من بلدة الفحيص ومحيطها. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الفحيص",
    serviceName: "خدمة شراء الأثاث المستعمل في الفحيص - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الفحيص: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Fuheis - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Fuheis and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Fuheis area and its surroundings in full. With over 60 years of experience, our team reaches you in Fuheis quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Fuheis, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Fuheis area?",
    faqAnswerEn: "Yes, we fully cover Fuheis and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Fuheis",
    serviceNameEn: "Used Furniture Buying Service in Fuheis - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Fuheis: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "mahes",
    nameAr: "ماحص",
    nameEn: "Mahes",
    metaTitle: "شراء أثاث مستعمل في ماحص - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في ماحص وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة ماحص بالكامل وضواحيها، بالقرب من بلدة ماحص. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في ماحص خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة ماحص، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة ماحص؟",
    faqAnswer: "نعم، نغطي منطقة ماحص بالكامل وضواحيها القريبة من بلدة ماحص. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في ماحص",
    serviceName: "خدمة شراء الأثاث المستعمل في ماحص - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في ماحص: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Mahes - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Mahes and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Mahes area and its surroundings in full. With over 60 years of experience, our team reaches you in Mahes quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Mahes, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Mahes area?",
    faqAnswerEn: "Yes, we fully cover Mahes and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Mahes",
    serviceNameEn: "Used Furniture Buying Service in Mahes - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Mahes: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "abu-alanda",
    nameAr: "أبو علندا",
    nameEn: "Abu Alanda",
    metaTitle: "شراء أثاث مستعمل في أبو علندا - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في أبو علندا وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة أبو علندا بالكامل وضواحيها، بالقرب من منطقة أبو علندا. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في أبو علندا خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة أبو علندا، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة أبو علندا؟",
    faqAnswer: "نعم، نغطي منطقة أبو علندا بالكامل وضواحيها القريبة من منطقة أبو علندا. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في أبو علندا",
    serviceName: "خدمة شراء الأثاث المستعمل في أبو علندا - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في أبو علندا: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Abu Alanda - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Abu Alanda and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Abu Alanda area and its surroundings in full. With over 60 years of experience, our team reaches you in Abu Alanda quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Abu Alanda, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Abu Alanda area?",
    faqAnswerEn: "Yes, we fully cover Abu Alanda and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Abu Alanda",
    serviceNameEn: "Used Furniture Buying Service in Abu Alanda - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Abu Alanda: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "marka",
    nameAr: "ماركا",
    nameEn: "Marka",
    metaTitle: "شراء أثاث مستعمل في ماركا - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في ماركا وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة ماركا بالكامل وضواحيها، بالقرب من منطقة ماركا الشمالية والجنوبية. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في ماركا خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة ماركا، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة ماركا؟",
    faqAnswer: "نعم، نغطي منطقة ماركا بالكامل وضواحيها القريبة من منطقة ماركا الشمالية والجنوبية. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في ماركا",
    serviceName: "خدمة شراء الأثاث المستعمل في ماركا - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في ماركا: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Marka - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Marka and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Marka area and its surroundings in full. With over 60 years of experience, our team reaches you in Marka quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Marka, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Marka area?",
    faqAnswerEn: "Yes, we fully cover Marka and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Marka",
    serviceNameEn: "Used Furniture Buying Service in Marka - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Marka: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "naour",
    nameAr: "ناعور",
    nameEn: "Naour",
    metaTitle: "شراء أثاث مستعمل في ناعور - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في ناعور وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة ناعور بالكامل وضواحيها، بالقرب من بلدة ناعور. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في ناعور خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة ناعور، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة ناعور؟",
    faqAnswer: "نعم، نغطي منطقة ناعور بالكامل وضواحيها القريبة من بلدة ناعور. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في ناعور",
    serviceName: "خدمة شراء الأثاث المستعمل في ناعور - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في ناعور: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Naour - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Naour and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Naour area and its surroundings in full. With over 60 years of experience, our team reaches you in Naour quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Naour, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Naour area?",
    faqAnswerEn: "Yes, we fully cover Naour and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Naour",
    serviceNameEn: "Used Furniture Buying Service in Naour - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Naour: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "muqabalain",
    nameAr: "المقابلين",
    nameEn: "Muqabalain",
    metaTitle: "شراء أثاث مستعمل في المقابلين - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في المقابلين وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة المقابلين بالكامل وضواحيها، بالقرب من منطقة المقابلين. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في المقابلين خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة المقابلين، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة المقابلين؟",
    faqAnswer: "نعم، نغطي منطقة المقابلين بالكامل وضواحيها القريبة من منطقة المقابلين. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في المقابلين",
    serviceName: "خدمة شراء الأثاث المستعمل في المقابلين - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في المقابلين: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Muqabalain - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Muqabalain and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Muqabalain area and its surroundings in full. With over 60 years of experience, our team reaches you in Muqabalain quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Muqabalain, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Muqabalain area?",
    faqAnswerEn: "Yes, we fully cover Muqabalain and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Muqabalain",
    serviceNameEn: "Used Furniture Buying Service in Muqabalain - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Muqabalain: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "hashmi",
    nameAr: "الهاشمي",
    nameEn: "Hashmi",
    metaTitle: "شراء أثاث مستعمل في الهاشمي - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الهاشمي وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الهاشمي بالكامل وضواحيها، بالقرب من الهاشمي الشمالي والجنوبي. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في الهاشمي خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الهاشمي، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الهاشمي؟",
    faqAnswer: "نعم، نغطي منطقة الهاشمي بالكامل وضواحيها القريبة من الهاشمي الشمالي والجنوبي. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الهاشمي",
    serviceName: "خدمة شراء الأثاث المستعمل في الهاشمي - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الهاشمي: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Hashmi - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Hashmi and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Hashmi area and its surroundings in full. With over 60 years of experience, our team reaches you in Hashmi quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Hashmi, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Hashmi area?",
    faqAnswerEn: "Yes, we fully cover Hashmi and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Hashmi",
    serviceNameEn: "Used Furniture Buying Service in Hashmi - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Hashmi: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "yajouz",
    nameAr: "ياجوز",
    nameEn: "Yajouz",
    metaTitle: "شراء أثاث مستعمل في ياجوز - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في ياجوز وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة ياجوز بالكامل وضواحيها، بالقرب من منطقة ياجوز. مع خبرة تمتد لأكثر من 60 عاماً، فريقنا يوصلك لموقعك في ياجوز خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة ياجوز، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة ياجوز؟",
    faqAnswer: "نعم، نغطي منطقة ياجوز بالكامل وضواحيها القريبة من منطقة ياجوز. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في ياجوز",
    serviceName: "خدمة شراء الأثاث المستعمل في ياجوز - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في ياجوز: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Yajouz - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Yajouz and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Yajouz area and its surroundings in full. With over 60 years of experience, our team reaches you in Yajouz quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Yajouz, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Yajouz area?",
    faqAnswerEn: "Yes, we fully cover Yajouz and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Yajouz",
    serviceNameEn: "Used Furniture Buying Service in Yajouz - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Yajouz: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "khalda",
    nameAr: "خلدا",
    nameEn: "Khalda",
    metaTitle: "شراء عفش وأثاث مستعمل في خلدا - عمان | الدابوقي",
    metaDescription: "نشتري العفش والأثاث المستعمل في خلدا وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة خلدا بالكامل وضواحيها، بالقرب من دوار خلدا، شارع الملكة رانيا، وسنتر بوينت. فريقنا يوصلك لموقعك في خلدا خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة خلدا، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة خلدا؟",
    faqAnswer: "نعم، نغطي منطقة خلدا بالكامل وضواحيها القريبة من دوار خلدا، شارع الملكة رانيا، وسنتر بوينت. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في خلدا",
    serviceName: "خدمة شراء الأثاث المستعمل في خلدا - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في خلدا: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Khalda - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Khalda and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Khalda area and its surroundings in full. With over 60 years of experience, our team reaches you in Khalda quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Khalda, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Khalda area?",
    faqAnswerEn: "Yes, we fully cover Khalda and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Khalda",
    serviceNameEn: "Used Furniture Buying Service in Khalda - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Khalda: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "shafa-badran",
    nameAr: "شفا بدران",
    nameEn: "Shafa Badran",
    metaTitle: "شراء أثاث مستعمل في شفا بدران - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في شفا بدران وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة شفا بدران بالكامل وضواحيها، بالقرب من مجمع النقابات المهنية ومنطقة المستودعات. فريقنا يوصلك لموقعك في شفا بدران خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة شفا بدران، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة شفا بدران؟",
    faqAnswer: "نعم، نغطي منطقة شفا بدران بالكامل وضواحيها القريبة من مجمع النقابات المهنية ومنطقة المستودعات. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في شفا بدران",
    serviceName: "خدمة شراء الأثاث المستعمل في شفا بدران - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في شفا بدران: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Shafa Badran - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Shafa Badran and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Shafa Badran area and its surroundings in full. With over 60 years of experience, our team reaches you in Shafa Badran quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Shafa Badran, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Shafa Badran area?",
    faqAnswerEn: "Yes, we fully cover Shafa Badran and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Shafa Badran",
    serviceNameEn: "Used Furniture Buying Service in Shafa Badran - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Shafa Badran: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "tlaa-al-ali",
    nameAr: "تلاع العلي",
    nameEn: "Tlaa Al Ali",
    metaTitle: "شراء أثاث مستعمل في تلاع العلي - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في تلاع العلي وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة تلاع العلي بالكامل وضواحيها، بالقرب من شارع مكة والمدارس المحيطة بتلاع العلي. فريقنا يوصلك لموقعك في تلاع العلي خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة تلاع العلي، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة تلاع العلي؟",
    faqAnswer: "نعم، نغطي منطقة تلاع العلي بالكامل وضواحيها القريبة من شارع مكة والمدارس المحيطة بتلاع العلي. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في تلاع العلي",
    serviceName: "خدمة شراء الأثاث المستعمل في تلاع العلي - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في تلاع العلي: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Tlaa Al Ali - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Tlaa Al Ali and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Tlaa Al Ali area and its surroundings in full. With over 60 years of experience, our team reaches you in Tlaa Al Ali quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Tlaa Al Ali, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Tlaa Al Ali area?",
    faqAnswerEn: "Yes, we fully cover Tlaa Al Ali and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Tlaa Al Ali",
    serviceNameEn: "Used Furniture Buying Service in Tlaa Al Ali - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Tlaa Al Ali: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "shmeisani",
    nameAr: "الشميساني",
    nameEn: "Shmeisani",
    metaTitle: "شراء أثاث مستعمل في الشميساني - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الشميساني وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الشميساني بالكامل وضواحيها، بالقرب من المنطقة المصرفية وشارع الشريف عبد الحميد شرف. فريقنا يوصلك لموقعك في الشميساني خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الشميساني، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الشميساني؟",
    faqAnswer: "نعم، نغطي منطقة الشميساني بالكامل وضواحيها القريبة من المنطقة المصرفية وشارع الشريف عبد الحميد شرف. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الشميساني",
    serviceName: "خدمة شراء الأثاث المستعمل في الشميساني - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الشميساني: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Shmeisani - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Shmeisani and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Shmeisani area and its surroundings in full. With over 60 years of experience, our team reaches you in Shmeisani quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Shmeisani, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Shmeisani area?",
    faqAnswerEn: "Yes, we fully cover Shmeisani and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Shmeisani",
    serviceNameEn: "Used Furniture Buying Service in Shmeisani - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Shmeisani: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "abdoun",
    nameAr: "عبدون",
    nameEn: "Abdoun",
    metaTitle: "شراء أثاث مستعمل في عبدون - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في عبدون وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة عبدون بالكامل وضواحيها، بالقرب من عبدون الشمالي والجسر وشارع السفارات. فريقنا يوصلك لموقعك في عبدون خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة عبدون، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة عبدون؟",
    faqAnswer: "نعم، نغطي منطقة عبدون بالكامل وضواحيها القريبة من عبدون الشمالي والجسر وشارع السفارات. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في عبدون",
    serviceName: "خدمة شراء الأثاث المستعمل في عبدون - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في عبدون: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Abdoun - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Abdoun and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Abdoun area and its surroundings in full. With over 60 years of experience, our team reaches you in Abdoun quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Abdoun, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Abdoun area?",
    faqAnswerEn: "Yes, we fully cover Abdoun and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Abdoun",
    serviceNameEn: "Used Furniture Buying Service in Abdoun - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Abdoun: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "jubaiha",
    nameAr: "الجبيهة",
    nameEn: "Jubaiha",
    metaTitle: "شراء أثاث مستعمل في الجبيهة - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في الجبيهة وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة الجبيهة بالكامل وضواحيها، بالقرب من الجامعة الأردنية ومنطقة الجبيهة الجديدة. فريقنا يوصلك لموقعك في الجبيهة خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة الجبيهة، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة الجبيهة؟",
    faqAnswer: "نعم، نغطي منطقة الجبيهة بالكامل وضواحيها القريبة من الجامعة الأردنية ومنطقة الجبيهة الجديدة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في الجبيهة",
    serviceName: "خدمة شراء الأثاث المستعمل في الجبيهة - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في الجبيهة: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Jubaiha - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Jubaiha and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Jubaiha area and its surroundings in full. With over 60 years of experience, our team reaches you in Jubaiha quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Jubaiha, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Jubaiha area?",
    faqAnswerEn: "Yes, we fully cover Jubaiha and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Jubaiha",
    serviceNameEn: "Used Furniture Buying Service in Jubaiha - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Jubaiha: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "sweileh",
    nameAr: "صويلح",
    nameEn: "Sweileh",
    metaTitle: "شراء أثاث مستعمل في صويلح - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في صويلح وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة صويلح بالكامل وضواحيها، بالقرب من دوار صويلح وشارع الأميرة بسمة. فريقنا يوصلك لموقعك في صويلح خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة صويلح، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة صويلح؟",
    faqAnswer: "نعم، نغطي منطقة صويلح بالكامل وضواحيها القريبة من دوار صويلح وشارع الأميرة بسمة. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في صويلح",
    serviceName: "خدمة شراء الأثاث المستعمل في صويلح - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في صويلح: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Sweileh - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Sweileh and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Sweileh area and its surroundings in full. With over 60 years of experience, our team reaches you in Sweileh quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Sweileh, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Sweileh area?",
    faqAnswerEn: "Yes, we fully cover Sweileh and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Sweileh",
    serviceNameEn: "Used Furniture Buying Service in Sweileh - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Sweileh: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
  {
    slug: "abdali",
    nameAr: "العبدلي",
    nameEn: "Abdali",
    metaTitle: "شراء أثاث مستعمل في العبدلي - عمان | الدابوقي",
    metaDescription: "نشتري الأثاث المستعمل في العبدلي وضواحيها: غرف نوم، صالونات، مكاتب، أجهزة كهربائية. معاينة مجانية فورية ودفع نقدي في موقعك. اتصل: 0796983994",
    intro: "شركة الدابوقي تغطي منطقة العبدلي بالكامل وضواحيها، بالقرب من منطقة العبدلي الجديدة وشارع الملك حسين. فريقنا يوصلك لموقعك في العبدلي خلال وقت قصير، ويشتري جميع أنواع الأثاث المستعمل بغض النظر عن حالته: غرف نوم كاملة، صالونات وأطقم جلوس، طاولات طعام، خزائن ملابس، مكاتب منزلية، أجهزة كهربائية وكل ما يتعلق بالمنزل والمكتب. نقوم بمعاينة الأثاث في موقعك بمنطقة العبدلي، تقديم تقييم عادل ومنصف، والدفع نقداً فوراً بعد الاتفاق.",
    faqQuestion: "هل تغطون منطقة العبدلي؟",
    faqAnswer: "نعم، نغطي منطقة العبدلي بالكامل وضواحيها القريبة من منطقة العبدلي الجديدة وشارع الملك حسين. عادة نوصل خلال نفس اليوم أو اليوم التالي لمعاينة الأثاث ودفع الثمن نقدًا فور الاتفاق على السعر.",
    serviceType: "شراء أثاث مستعمل في العبدلي",
    serviceName: "خدمة شراء الأثاث المستعمل في العبدلي - عمان",
    serviceDescription: "نشتري جميع أنواع الأثاث المستعمل في العبدلي: غرف نوم، صالونات، مكاتب، أجهزة كهربائية بأفضل الأسعار مع معاينة فورية في موقعك",
    metaTitleEn: "Buy Used Furniture in Abdali - Amman | Aldabouqi",
    metaDescriptionEn: "We buy used furniture in Abdali and nearby areas: bedrooms, living rooms, offices, appliances. Free instant inspection and cash payment at your location. Call: 0796983994",
    introEn: "Aldabouqi covers the Abdali area and its surroundings in full. With over 60 years of experience, our team reaches you in Abdali quickly and buys all types of used furniture regardless of condition: complete bedrooms, sofas and seating sets, dining tables, wardrobes, home offices, appliances, and everything related to your home or office. We inspect the furniture at your location in Abdali, offer a fair and honest valuation, and pay cash immediately once agreed.",
    faqQuestionEn: "Do you cover the Abdali area?",
    faqAnswerEn: "Yes, we fully cover Abdali and its nearby surroundings. We usually reach you the same day or the next day to inspect the furniture and pay cash on the spot once a price is agreed.",
    serviceTypeEn: "Buying Used Furniture in Abdali",
    serviceNameEn: "Used Furniture Buying Service in Abdali - Amman",
    serviceDescriptionEn: "We buy all types of used furniture in Abdali: bedrooms, sofas, offices, appliances at the best prices with an instant inspection at your location",
  },
];

export function getAreaBySlug(slug: string) {
  return areas.find((a) => a.slug === slug);
}
