import { sql } from "drizzle-orm";
import { getDb } from "../src/db";
import { products } from "../src/db/schema";

// Idempotent upsert (re-runnable) so it can safely bring a database that
// already has the original 2 products up to a full 8-category catalog for
// QA/preview. images is deliberately [] on every row — real photos get
// added later through the admin panel; until then ProductImagePlaceholder
// renders an honest "photo coming soon" state instead of a stock photo.
const rows = [
  {
    slug: "bedroom-set-turkish-1",
    titleAr: "غرفة نوم تركي مستعملة",
    titleEn: "Used Turkish Bedroom Set",
    descriptionAr: "غرفة نوم تركي بحالة ممتازة، تشمل دولاب 6 أبواب وسرير وكومودينتين.",
    descriptionEn: "Turkish bedroom set in excellent condition, includes a 6-door wardrobe, bed, and two nightstands.",
    category: "bedrooms",
    condition: "excellent" as const,
    price: 250,
    area: "khalda",
    status: "available" as const,
    images: [],
  },
  {
    slug: "bedroom-set-classic-2",
    titleAr: "غرفة نوم كلاسيك خشب زان",
    titleEn: "Classic Beech Wood Bedroom Set",
    descriptionAr: "غرفة نوم خشب زان أصلي، سرير مقاس كبير مع دولاب 4 أبواب، حالة جيدة جداً.",
    descriptionEn: "Solid beech wood bedroom set, king-size bed with a 4-door wardrobe, very good condition.",
    category: "bedrooms",
    condition: "good" as const,
    price: 180,
    area: "sweifieh",
    status: "available" as const,
    images: [],
  },
  {
    slug: "office-desk-set-1",
    titleAr: "طقم مكتب إداري مستعمل",
    titleEn: "Used Executive Office Desk Set",
    descriptionAr: "مكتب إداري مع كرسي وخزانة ملفات جانبية، حالة جيدة جداً.",
    descriptionEn: "Executive desk with chair and side filing cabinet, very good condition.",
    category: "offices",
    condition: "good" as const,
    price: null,
    area: "shmeisani",
    status: "available" as const,
    images: [],
  },
  {
    slug: "office-chair-ergonomic-1",
    titleAr: "كرسي مكتب مريح مستعمل",
    titleEn: "Used Ergonomic Office Chair",
    descriptionAr: "كرسي مكتب مريح بمساند للذراعين، مناسب للاستخدام الطويل، حالة ممتازة.",
    descriptionEn: "Ergonomic office chair with armrests, great for long working hours, excellent condition.",
    category: "offices",
    condition: "excellent" as const,
    price: 45,
    area: "abdali",
    status: "available" as const,
    images: [],
  },
  {
    slug: "salon-corner-set-1",
    titleAr: "صالون ركني 7 مقاعد",
    titleEn: "7-Seater Corner Sofa Set",
    descriptionAr: "صالون ركني قماش بيج، 7 مقاعد، حالة جيدة، مناسب لصالة استقبال واسعة.",
    descriptionEn: "Beige fabric corner sofa set, seats 7, good condition, great for a large living room.",
    category: "salons",
    condition: "good" as const,
    price: 220,
    area: "abdoun",
    status: "available" as const,
    images: [],
  },
  {
    slug: "salon-leather-set-1",
    titleAr: "كنبة جلد 3 مقاعد",
    titleEn: "3-Seater Leather Sofa",
    descriptionAr: "كنبة جلد طبيعي بني، 3 مقاعد، حالة ممتازة تقريباً بدون استخدام.",
    descriptionEn: "Genuine brown leather 3-seater sofa, excellent condition, barely used.",
    category: "salons",
    condition: "excellent" as const,
    price: 190,
    area: "khalda",
    status: "available" as const,
    images: [],
  },
  {
    slug: "washing-machine-1",
    titleAr: "غسالة أوتوماتيك مستعملة",
    titleEn: "Used Automatic Washing Machine",
    descriptionAr: "غسالة أوتوماتيك سعة 8 كيلو، شغالة بحالة ممتازة، فحص كهرباء متوفر.",
    descriptionEn: "8kg automatic washing machine, working perfectly, electrical check available on request.",
    category: "appliances",
    condition: "excellent" as const,
    price: 95,
    area: "tlaa-al-ali",
    status: "available" as const,
    images: [],
  },
  {
    slug: "refrigerator-1",
    titleAr: "ثلاجة مستعملة بابين",
    titleEn: "Used Double-Door Refrigerator",
    descriptionAr: "ثلاجة بابين نوسفروست، حالة جيدة جداً، بدون أي أعطال.",
    descriptionEn: "No-frost double-door refrigerator, very good condition, no issues.",
    category: "appliances",
    condition: "good" as const,
    price: 130,
    area: "sweileh",
    status: "available" as const,
    images: [],
  },
  {
    slug: "decor-mirror-set-1",
    titleAr: "مرايا ديكور مستعملة",
    titleEn: "Used Decorative Mirror Set",
    descriptionAr: "طقم مرايا ديكور بإطار ذهبي، حالة ممتازة، مناسبة للصالة أو المدخل.",
    descriptionEn: "Gold-framed decorative mirror set, excellent condition, great for a living room or entryway.",
    category: "other",
    condition: "excellent" as const,
    price: 30,
    area: "gardens",
    status: "available" as const,
    images: [],
  },
  {
    slug: "carpet-persian-1",
    titleAr: "سجادة عجمي مستعملة",
    titleEn: "Used Persian-Style Carpet",
    descriptionAr: "سجادة عجمي قياس كبير، ألوان دافئة، حالة جيدة جداً.",
    descriptionEn: "Large Persian-style carpet, warm colors, very good condition.",
    category: "other",
    condition: "good" as const,
    price: null,
    area: "jabal-amman",
    status: "available" as const,
    images: [],
  },
  {
    slug: "bedroom-no-wardrobe-1",
    titleAr: "غرفة نوم بدون خزانة (سرير وكومودينو)",
    titleEn: "Bedroom Set without Wardrobe (Bed + Nightstand)",
    descriptionAr: "سرير مقاس فردين مع كومودينو، بدون دولاب، حالة ممتازة، مناسبة لغرفة صغيرة.",
    descriptionEn: "Queen-size bed with a nightstand, no wardrobe included, excellent condition, ideal for a smaller room.",
    category: "bedrooms-no-wardrobe",
    condition: "excellent" as const,
    price: 110,
    area: "um-uthaina",
    status: "available" as const,
    images: [],
  },
  {
    slug: "bedroom-no-wardrobe-2",
    titleAr: "غرفة نوم شبابية بدون خزانة",
    titleEn: "Youth Bedroom Set without Wardrobe",
    descriptionAr: "سرير مفرد مع طاولة جانبية، مناسب لغرفة الشباب، حالة جيدة.",
    descriptionEn: "Single bed with a side table, suited for a youth room, good condition.",
    category: "bedrooms-no-wardrobe",
    condition: "good" as const,
    price: 70,
    area: "marka",
    status: "available" as const,
    images: [],
  },
  {
    slug: "dining-table-6-1",
    titleAr: "طاولة سفرة 6 كراسي",
    titleEn: "6-Seater Dining Table Set",
    descriptionAr: "طاولة سفرة خشب مع 6 كراسي مبطنة، حالة ممتازة، مناسبة للعائلات.",
    descriptionEn: "Wooden dining table with 6 upholstered chairs, excellent condition, great for families.",
    category: "dining-tables",
    condition: "excellent" as const,
    price: 160,
    area: "dahiyat-al-rashid",
    status: "available" as const,
    images: [],
  },
  {
    slug: "dining-table-4-1",
    titleAr: "طاولة سفرة 4 كراسي",
    titleEn: "4-Seater Dining Table Set",
    descriptionAr: "طاولة سفرة رخام صناعي مع 4 كراسي، حالة جيدة جداً.",
    descriptionEn: "Faux-marble dining table with 4 chairs, very good condition.",
    category: "dining-tables",
    condition: "good" as const,
    price: null,
    area: "naour",
    status: "available" as const,
    images: [],
  },
  {
    slug: "tv-smart-1",
    titleAr: "تلفزيون سمارت 50 بوصة",
    titleEn: "50-Inch Smart TV",
    descriptionAr: "تلفزيون سمارت 50 بوصة، شغال بحالة ممتازة مع الريموت الأصلي.",
    descriptionEn: "50-inch smart TV, working excellently, includes the original remote.",
    category: "electronics",
    condition: "excellent" as const,
    price: 140,
    area: "abu-nassir",
    status: "available" as const,
    images: [],
  },
  {
    slug: "ac-split-unit-1",
    titleAr: "مكيف سبليت مستعمل",
    titleEn: "Used Split Air Conditioner",
    descriptionAr: "مكيف سبليت 1.5 طن، شغال بحالة جيدة جداً، بدون تركيب.",
    descriptionEn: "1.5-ton split air conditioner, working in very good condition, uninstalled.",
    category: "electronics",
    condition: "good" as const,
    price: 85,
    area: "yajouz",
    status: "available" as const,
    images: [],
  },
];

async function main() {
  const db = getDb();
  for (const row of rows) {
    await db
      .insert(products)
      .values(row)
      .onConflictDoUpdate({
        target: products.slug,
        set: {
          titleAr: row.titleAr,
          titleEn: row.titleEn,
          descriptionAr: row.descriptionAr,
          descriptionEn: row.descriptionEn,
          category: row.category,
          condition: row.condition,
          price: row.price,
          area: row.area,
          status: row.status,
          updatedAt: sql`now()`,
        },
      });
  }
  console.log(`Upserted ${rows.length} products.`);
}

main();
